import { EVENTS } from '../../events/domain-events'

// request type → document_forms.category 매핑
export const REQUEST_TYPE_CATEGORY_MAP: Record<string, string> = {
  LEAVE_CREATE: 'leave_request',
  LEAVE_MODIFY: 'leave_request',
  LEAVE_DELETE: 'leave_request',
  SHIFT_CREATE: 'shift_change_request',
  SHIFT_MODIFY: 'shift_change_request',
  SHIFT_DELETE: 'shift_change_request',
  ATTENDANCE_EDIT: 'attendance_correction_request',
  ATTENDANCE_CREATE: 'attendance_correction_request',
  ATTENDANCE_DELETE: 'attendance_correction_request',
  DEVICE_CHANGE: 'device_change_request',
  OFFSITE_WORK: 'offsite_work_request',
  CUSTOM: 'custom_request',
}

// 상신 시 emit할 이벤트 매핑 (NotificationListener 구독 이름과 일치해야 함)
export const REQUEST_TYPE_REQUESTED_EVENT: Record<string, string> = {
  LEAVE_CREATE: EVENTS.LEAVE_REQUESTED,
  LEAVE_MODIFY: EVENTS.LEAVE_REQUESTED,
  LEAVE_DELETE: EVENTS.LEAVE_REQUESTED,
  SHIFT_CREATE: EVENTS.SHIFT_REQUESTED,
  SHIFT_MODIFY: EVENTS.SHIFT_REQUESTED,
  SHIFT_DELETE: EVENTS.SHIFT_REQUESTED,
  ATTENDANCE_EDIT: EVENTS.ATTENDANCE_REQUESTED,
  ATTENDANCE_CREATE: EVENTS.ATTENDANCE_REQUESTED,
  ATTENDANCE_DELETE: EVENTS.ATTENDANCE_REQUESTED,
  DEVICE_CHANGE: EVENTS.DEVICE_CHANGE_REQUESTED,
  OFFSITE_WORK: EVENTS.OFFSITE_WORK_REQUESTED,
  CUSTOM: EVENTS.CUSTOM_REQUESTED,
}

// 승인 완료 후 emit할 이벤트 매핑
export const REQUEST_TYPE_APPROVED_EVENT: Record<string, string> = {
  LEAVE_CREATE: EVENTS.LEAVE_APPROVED,
  LEAVE_MODIFY: EVENTS.LEAVE_APPROVED,
  LEAVE_DELETE: EVENTS.LEAVE_APPROVED,
  SHIFT_CREATE: EVENTS.SHIFT_APPROVED,
  SHIFT_MODIFY: EVENTS.SHIFT_APPROVED,
  SHIFT_DELETE: EVENTS.SHIFT_APPROVED,
  ATTENDANCE_EDIT: EVENTS.ATTENDANCE_APPROVED,
  ATTENDANCE_CREATE: EVENTS.ATTENDANCE_APPROVED,
  ATTENDANCE_DELETE: EVENTS.ATTENDANCE_APPROVED,
  DEVICE_CHANGE: EVENTS.DEVICE_CHANGE_APPROVED,
  OFFSITE_WORK: EVENTS.OFFSITE_WORK_APPROVED,
  CUSTOM: EVENTS.CUSTOM_APPROVED,
}

export const REQUEST_TYPE_REJECTED_EVENT: Record<string, string> = {
  LEAVE_CREATE: EVENTS.LEAVE_REJECTED,
  LEAVE_MODIFY: EVENTS.LEAVE_REJECTED,
  LEAVE_DELETE: EVENTS.LEAVE_REJECTED,
  SHIFT_CREATE: EVENTS.SHIFT_REJECTED,
  SHIFT_MODIFY: EVENTS.SHIFT_REJECTED,
  SHIFT_DELETE: EVENTS.SHIFT_REJECTED,
  ATTENDANCE_EDIT: EVENTS.ATTENDANCE_REJECTED,
  ATTENDANCE_CREATE: EVENTS.ATTENDANCE_REJECTED,
  ATTENDANCE_DELETE: EVENTS.ATTENDANCE_REJECTED,
  DEVICE_CHANGE: EVENTS.DEVICE_CHANGE_REJECTED,
  OFFSITE_WORK: EVENTS.OFFSITE_WORK_REJECTED,
  CUSTOM: EVENTS.CUSTOM_REJECTED,
}

/** 결재 규칙(라운드별 필수 승인 수 details 포함) — 다결재자/병렬(M-of-N) 판정용 */
export type RuleWithDetails = {
  maxApprovalRounds?: number
  details?: Array<{ round: number; requiredCount: number }>
} | null
